import type {
  Product,
  Material,
  Content,
  PublishTask,
  Platform,
  PublishLog,
  AnalyticsOverview,
  ContentPerformance,
  TrendData,
  PlatformDistribution,
} from './types'

export const mockProducts: Product[] = [
  {
    id: 1,
    asin: 'B0BVMHH9B7',
    title: 'Breville Barista Express 意式咖啡机',
    category: '咖啡机',
    price: 699.95,
    rating: 4.6,
    reviewCount: 12453,
    imageUrl: 'https://picsum.photos/seed/coffee1/400/400',
    status: 'researching',
    potentialScore: 92,
    createdAt: '2025-12-01',
  },
  {
    id: 2,
    asin: 'B09RLNJRM3',
    title: 'Lavazza Super Crema 意式咖啡豆 1kg',
    category: '咖啡豆',
    price: 18.98,
    rating: 4.5,
    reviewCount: 35821,
    imageUrl: 'https://picsum.photos/seed/coffee2/400/400',
    status: 'covered',
    potentialScore: 85,
    createdAt: '2025-11-28',
  },
  {
    id: 3,
    asin: 'B0CP8KZWQ1',
    title: 'Fellow Opus 锥刀磨豆机',
    category: '磨豆机',
    price: 195.0,
    rating: 4.3,
    reviewCount: 2156,
    imageUrl: 'https://picsum.photos/seed/coffee3/400/400',
    status: 'pending',
    potentialScore: 78,
    createdAt: '2025-12-05',
  },
  {
    id: 4,
    asin: 'B0B2HQDF1S',
    title: 'De\'Longhi Dinamica Plus 全自动咖啡机',
    category: '咖啡机',
    price: 1299.95,
    rating: 4.4,
    reviewCount: 5672,
    imageUrl: 'https://picsum.photos/seed/coffee4/400/400',
    status: 'pending',
    potentialScore: 88,
    createdAt: '2025-12-08',
  },
  {
    id: 5,
    asin: 'B07HGBKFLZ',
    title: 'Hario V60 手冲咖啡套装',
    category: '手冲器具',
    price: 29.99,
    rating: 4.7,
    reviewCount: 18923,
    imageUrl: 'https://picsum.photos/seed/coffee5/400/400',
    status: 'researching',
    potentialScore: 72,
    createdAt: '2025-11-15',
  },
  {
    id: 6,
    asin: 'B0CJ3K2PLN',
    title: 'Niche Zero 平刀磨豆机',
    category: '磨豆机',
    price: 729.0,
    rating: 4.8,
    reviewCount: 3210,
    imageUrl: 'https://picsum.photos/seed/coffee6/400/400',
    status: 'pending',
    potentialScore: 95,
    createdAt: '2025-12-10',
  },
]

export const mockMaterials: Material[] = [
  {
    id: 1,
    asin: 'B0BVMHH9B7',
    sourceType: 'amazon_review',
    sourceUrl: 'https://amazon.com/review/1',
    content: '这款咖啡机的蒸汽喷嘴非常强大，可以打出丝滑的奶泡。压力稳定，出品很不错...',
    sentimentScore: 0.85,
    createdAt: '2025-12-02',
  },
  {
    id: 2,
    asin: 'B0BVMHH9B7',
    sourceType: 'youtube',
    sourceUrl: 'https://youtube.com/watch?v=abc123',
    content: 'James Hoffmann 深度评测 Breville Barista Express，从研磨到萃取全面分析...',
    sentimentScore: 0.78,
    createdAt: '2025-12-03',
  },
  {
    id: 3,
    asin: 'B0BVMHH9B7',
    sourceType: 'reddit',
    sourceUrl: 'https://reddit.com/r/coffee/post1',
    content: '使用半年的长期使用报告，对比了同价位的 Gaggia Classic Pro...',
    sentimentScore: 0.72,
    createdAt: '2025-12-04',
  },
  {
    id: 4,
    asin: 'B09RLNJRM3',
    sourceType: 'amazon_review',
    sourceUrl: 'https://amazon.com/review/2',
    content: '性价比很高的咖啡豆，适合日常饮用。烘焙度适中，不会太苦...',
    sentimentScore: 0.88,
    createdAt: '2025-11-30',
  },
  {
    id: 5,
    asin: 'B09RLNJRM3',
    sourceType: 'quora',
    sourceUrl: 'https://quora.com/answer/123',
    content: '关于 Lavazza 咖啡豆的新鲜度和保质期的讨论，多位咖啡爱好者给出了建议...',
    sentimentScore: 0.65,
    createdAt: '2025-12-01',
  },
  {
    id: 6,
    asin: 'B0CP8KZWQ1',
    sourceType: 'youtube',
    sourceUrl: 'https://youtube.com/watch?v=def456',
    content: 'Fellow Opus 与 Baratza Encore ESP 的对比评测，研磨均匀度测试...',
    sentimentScore: 0.81,
    createdAt: '2025-12-06',
  },
]

export const mockContents: Content[] = [
  {
    id: 1,
    slug: 'breville-barista-express-review-2025',
    asin: 'B0BVMHH9B7',
    title: 'Breville Barista Express 2025 深度评测：家用意式咖啡机的最佳选择？',
    type: 'review',
    content: '在家用意式咖啡机市场中，Breville Barista Express 一直是热门之选...',
    status: 'published',
    aiGenerated: true,
    humanReviewed: true,
    wordCount: 3200,
    createdAt: '2025-12-05',
    updatedAt: '2025-12-08',
  },
  {
    id: 2,
    slug: 'coffee-bean-buying-guide',
    asin: 'B09RLNJRM3',
    title: '2025 咖啡豆选购指南：从入门到精通',
    type: 'guide',
    content: '选择合适的咖啡豆是冲泡一杯好咖啡的第一步...',
    status: 'reviewing',
    aiGenerated: true,
    humanReviewed: false,
    wordCount: 4500,
    createdAt: '2025-12-08',
    updatedAt: '2025-12-08',
  },
  {
    id: 3,
    slug: 'espresso-extraction-science',
    asin: 'B0BVMHH9B7',
    title: '意式咖啡萃取的科学：温度、压力与研磨度的完美平衡',
    type: 'science',
    content: '意式咖啡萃取是一个复杂的化学过程...',
    status: 'draft',
    aiGenerated: true,
    humanReviewed: false,
    wordCount: 2800,
    createdAt: '2025-12-10',
    updatedAt: '2025-12-10',
  },
  {
    id: 4,
    slug: 'fellow-opus-grinder-review',
    asin: 'B0CP8KZWQ1',
    title: 'Fellow Opus 磨豆机评测：设计与功能的完美融合',
    type: 'review',
    content: 'Fellow 以其简约的设计美学闻名...',
    status: 'approved',
    aiGenerated: true,
    humanReviewed: true,
    wordCount: 2600,
    createdAt: '2025-12-09',
    updatedAt: '2025-12-11',
  },
  {
    id: 5,
    slug: 'home-coffee-machine-comparison',
    asin: 'B0B2HQDF1S',
    title: '家用全自动 vs 半自动咖啡机：哪种更适合你？',
    type: 'guide',
    content: '选择咖啡机时，全自动和半自动是最常见的两种选择...',
    status: 'draft',
    aiGenerated: false,
    humanReviewed: false,
    wordCount: 3800,
    createdAt: '2025-12-11',
    updatedAt: '2025-12-11',
  },
]

export const mockPublishTasks: PublishTask[] = [
  {
    id: 1,
    contentId: 1,
    contentTitle: 'Breville Barista Express 2025 深度评测',
    platforms: ['Blogger', 'Medium'],
    status: 'success',
    results: [
      { platform: 'Blogger', status: 'success', url: 'https://blog.example.com/post1' },
      { platform: 'Medium', status: 'success', url: 'https://medium.com/@user/post1' },
    ],
    createdAt: '2025-12-08 14:30',
  },
  {
    id: 2,
    contentId: 4,
    contentTitle: 'Fellow Opus 磨豆机评测',
    platforms: ['Blogger', 'WordPress', 'Medium'],
    status: 'running',
    results: [
      { platform: 'Blogger', status: 'success', url: 'https://blog.example.com/post2' },
    ],
    createdAt: '2025-12-11 10:15',
  },
  {
    id: 3,
    contentId: 2,
    contentTitle: '2025 咖啡豆选购指南',
    platforms: ['Blogger'],
    status: 'failed',
    results: [
      { platform: 'Blogger', status: 'failed', error: 'API 认证失败，请检查配置' },
    ],
    createdAt: '2025-12-10 16:45',
  },
  {
    id: 4,
    contentId: 5,
    contentTitle: '家用全自动 vs 半自动咖啡机',
    platforms: ['Medium', 'WordPress'],
    status: 'pending',
    results: [],
    createdAt: '2025-12-11 11:00',
  },
]

export const mockPlatforms: Platform[] = [
  { id: 1, name: 'Blogger', enabled: true, icon: 'B', configured: true },
  { id: 2, name: 'Medium', enabled: true, icon: 'M', configured: true },
  { id: 3, name: 'WordPress', enabled: false, icon: 'W', configured: false },
  { id: 4, name: 'Ghost', enabled: false, icon: 'G', configured: false },
  { id: 5, name: 'Substack', enabled: false, icon: 'S', configured: false },
]

export const mockPublishLogs: PublishLog[] = [
  {
    id: 1,
    message: '成功发布 "Breville Barista Express 2025 深度评测" 到 Blogger',
    type: 'success',
    timestamp: '2025-12-08 14:32',
  },
  {
    id: 2,
    message: '成功发布 "Breville Barista Express 2025 深度评测" 到 Medium',
    type: 'success',
    timestamp: '2025-12-08 14:35',
  },
  {
    id: 3,
    message: '发布 "2025 咖啡豆选购指南" 到 Blogger 失败：API 认证失败',
    type: 'danger',
    timestamp: '2025-12-10 16:48',
  },
  {
    id: 4,
    message: '正在发布 "Fellow Opus 磨豆机评测" 到 Blogger...',
    type: 'info',
    timestamp: '2025-12-11 10:16',
  },
  {
    id: 5,
    message: '成功发布 "Fellow Opus 磨豆机评测" 到 Blogger',
    type: 'success',
    timestamp: '2025-12-11 10:18',
  },
  {
    id: 6,
    message: '正在发布 "Fellow Opus 磨豆机评测" 到 WordPress...',
    type: 'warning',
    timestamp: '2025-12-11 10:19',
  },
]

export const mockAnalytics: AnalyticsOverview = {
  totalRevenue: 2847.5,
  revenueTrend: 12.5,
  totalViews: 156432,
  viewsTrend: 8.3,
  conversionRate: 3.2,
  conversionTrend: -0.5,
  publishedCount: 24,
  publishedTrend: 20,
}

export const mockContentPerformance: ContentPerformance[] = [
  { id: 1, title: 'Breville Barista Express 2025 深度评测', views: 45230, clicks: 3821, conversions: 156, revenue: 892.50 },
  { id: 2, title: '2025 咖啡豆选购指南', views: 32100, clicks: 2560, conversions: 89, revenue: 534.00 },
  { id: 3, title: '家用全自动 vs 半自动咖啡机', views: 28750, clicks: 2140, conversions: 72, revenue: 468.30 },
  { id: 4, title: 'Fellow Opus 磨豆机评测', views: 21300, clicks: 1890, conversions: 45, revenue: 351.20 },
  { id: 5, title: '意式咖啡萃取的科学', views: 18400, clicks: 1250, conversions: 28, revenue: 198.50 },
]

export const mockTrendData: TrendData[] = [
  { date: '12/01', revenue: 120, views: 8200 },
  { date: '12/02', revenue: 85, views: 7500 },
  { date: '12/03', revenue: 145, views: 9800 },
  { date: '12/04', revenue: 168, views: 11200 },
  { date: '12/05', revenue: 210, views: 14500 },
  { date: '12/06', revenue: 195, views: 13200 },
  { date: '12/07', revenue: 230, views: 15800 },
  { date: '12/08', revenue: 280, views: 18400 },
  { date: '12/09', revenue: 245, views: 16700 },
  { date: '12/10', revenue: 310, views: 21300 },
  { date: '12/11', revenue: 295, views: 19800 },
]

export const mockPlatformDistribution: PlatformDistribution[] = [
  { name: 'Blogger', value: 45, fill: '#2563eb' },
  { name: 'Medium', value: 30, fill: '#10b981' },
  { name: 'WordPress', value: 15, fill: '#f59e0b' },
  { name: '其他', value: 10, fill: '#6b7280' },
]
